{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argovue.serviceAccountName" . }}
  labels:
{{ include "argovue.labels" . | nindent 4 }}
{{- end -}}
