{{- if .Values.dex.enabled -}}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "argovue.fullname" . }}-dex
data:
  config.yaml: |-
{{- with .Values.dex }}
    issuer: {{ .issuer }}
    storage:
      type: kubernetes
      config:
        inCluster: true
    web:
      http: 0.0.0.0:5556
    logger:
{{ toYaml .logger | indent 6 }}
{{- if .connectors }}
    connectors:
{{ toYaml .connectors | indent 4 }}
{{- end }}
    oauth2: {{ toYaml .oauth2 | nindent 6 }}
{{- if .staticClients }}
    staticClients:
{{ toYaml .staticClients | indent 4 }}
    {{- end }}
    enablePasswordDB: {{ .enablePasswordDB }}
{{- if .staticPasswords }}
    staticPasswords:
{{ toYaml .staticPasswords | indent 4 }}
{{- end }}
{{- if .expiry }}
    expiry:
{{ toYaml .expiry | indent 6 }}
{{- end }}
{{- if .frontend }}
    frontend: {{ toYaml .frontend | nindent 6 }}
{{- end }}
{{- end }}
{{- end -}}